// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfHjEIzFzSPlPhfy05JM6pPOrMk0aBSAc',
    appId: '1:473866367991:web:71683119d70850a33d34f2',
    messagingSenderId: '473866367991',
    projectId: 'whatsapp-flutter-b5efe',
    authDomain: 'whatsapp-flutter-b5efe.firebaseapp.com',
    storageBucket: 'whatsapp-flutter-b5efe.appspot.com',
    measurementId: 'G-P24WZVJDV2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKxOUSP5Qa65BuZP9076pHEy35iKTeeXw',
    appId: '1:473866367991:android:a0bb6d96d11c73733d34f2',
    messagingSenderId: '473866367991',
    projectId: 'whatsapp-flutter-b5efe',
    storageBucket: 'whatsapp-flutter-b5efe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8JM4cmyZUGegFhS8J8eT8xsKwmxw6sg4',
    appId: '1:473866367991:ios:121e9c4bd286cf783d34f2',
    messagingSenderId: '473866367991',
    projectId: 'whatsapp-flutter-b5efe',
    storageBucket: 'whatsapp-flutter-b5efe.appspot.com',
    iosClientId: '473866367991-ri2d0qa2ii7hojphvhqak1bncs5tqjor.apps.googleusercontent.com',
    iosBundleId: 'com.pradyotprakash.whatsapp.clone.whatsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8JM4cmyZUGegFhS8J8eT8xsKwmxw6sg4',
    appId: '1:473866367991:ios:121e9c4bd286cf783d34f2',
    messagingSenderId: '473866367991',
    projectId: 'whatsapp-flutter-b5efe',
    storageBucket: 'whatsapp-flutter-b5efe.appspot.com',
    iosClientId: '473866367991-ri2d0qa2ii7hojphvhqak1bncs5tqjor.apps.googleusercontent.com',
    iosBundleId: 'com.pradyotprakash.whatsapp.clone.whatsapp',
  );
}
