class Constants:
    class Messages:
        STARTING_MESSAGE = """
Welcome to the tutorial. Here we will be taking look on various Python related basics. 
Each operations output will be shown on the console and you can navigate to the files for how it's being achieved."""
        LETS_START_WITH_PYTHON = "Let's start with {} in python"
        NUMBERS_START = "numbers"
        VARIABLES_ASSIGNMENT_START = "variable assignments"
        STRINGS_START = "Strings basics"
        STRINGS_SLICING_INDEXING = "Strings slicing and indexing"
        STRINGS_PROPERTIES_METHODS = "Strings properties and methods"
        STRINGS_FORMATTING = "formatting Strings"
        LISTS = "Lists"
        DICTIONARIES = "Dictionaries"
        TUPLES = "Tuples"
        SETS = "Sets"
        BOOLEANS = "Booleans"
        IO_WITH_FILES = "I/O with Files"
        COMPARISON_LOGICAL_OPERATORS = "Comparison Operators and Logical Operators"
        IF_ELIF_ELSE = "If, elif and else"
        FOR_LOOPS = "For loops"
        WHILE_LOOPS = "While loops"
