class Constants:
    class Messages:
        STARTING_MESSAGE = """
Welcome to the tutorial. Here we will be taking look on various Python related basics. 
Each operations output will be shown on the console and you can navigate to the files for how it's being achieved."""
        LETS_START_WITH_PYTHON = "Let's start with {} in python"
        NUMBERS_START = "numbers"
        VARIABLES_ASSIGNMENT_START = "variable assignments"
        STRINGS_START = "Strings basics"
        STRINGS_SLICING_INDEXING = "Strings slicing and indexing"
        STRINGS_PROPERTIES_METHODS = "Strings properties and methods"
        STRINGS_FORMATTING = "formatting Strings"
        LISTS = "Lists"
        DICTIONARIES = "Dictionaries"
        TUPLES = "Tuples"
        SETS = "Sets"
        BOOLEANS = "Booleans"
        IO_WITH_FILES = "I/O with Files"
        COMPARISON_LOGICAL_OPERATORS = "Comparison Operators and Logical Operators"
        IF_ELIF_ELSE = "If, elif and else"
        FOR_LOOPS = "For loops"
        WHILE_LOOPS = "While loops"
        USEFUL_OPERATORS = "Useful operators"
        LIST_COMPREHENSION = "List comprehension"
        METHODS_FUNCTIONS = "Methods and Functions"
        THREE_CUP_MONTEE = "Let's create a three cup montee game using Python"
        ARGS_KWARGS = "*args and **kwargs"
        LAMBDA_FILTERS_MAPS = "Lambda expressions, filters and maps"
        NESTED_STATEMENTS_SCOPES = "Nested statements and scopes"
        TIC_TAC_TOE = "Tic-Tac-Toe game"
        WELCOME_TO_TIC_TAC_TOE = f"Welcome to the {TIC_TAC_TOE}. Below is the current state of the game."
        ATTRIBUTES_CLASS_KEYWORD = "Attributes and class keyword"
        CLASS_OBJECT_ATTRIBUTES_METHODS = "Class object attributes and methods"
        INHERITANCE_POLYMORPHISM = "Inheritance and Polymorphism"
        SPECIAL_METHODS = "Special methods (OOPs)"
        ERRORS_EXCEPTION_HANDLING = "Errors and exception handling"
        WAR_DECK_GAME = "War deck game"
        BLACKJACK_GAME = "Blackjack game"
        DECORATORS = "Decorators"
        GENERATORS = "Generators"
        COLLECTION_MODULE = "Collections"
        OS_MODULE = "Opening and reading files and folder"
        DATE_TIME_MODULE = "Datetime Module"
        MATH_RANDOM_MODULE = "Math and Random module"
        PYTHON_DEBUGGER = "Python Debugger"
        REGULAR_EXPRESSIONS = "Regular Expressions"
        TIMING_CODE = "Timing Code"
        ZIP_UNZIP_FILE = "Zip and Unzip Files"
