package core.utils

import core.utils.Constants.ConstValues.PASSWORD_LENGTH
import core.utils.Constants.ConstValues.USERNAME_LENGTH

object Localization {
    const val APP_NAME = "X"
    const val SPLASH_SCREEN_MESSAGE = "See what's happening in the work right now."
    const val CONTINUE_WITH_GOOGLE = "Continue with Google"
    const val CREATE_ACCOUNT = "Create Account"
    const val OR = "or"
    const val BY_SIGNING_UP = "By signing up, you agree to our"
    const val TERMS = "Terms"
    const val PRIVACY_POLICY = "Privacy Policy"
    const val AND = "and"
    const val COOKIE_USE = "Cookie Use"
    const val COMMA = ","
    const val FULL_STOP = "."
    const val WHITE_SPACE = " "
    const val HAVE_AN_ACCOUNT = "Have an account?"
    const val LOG_IN = "Log in"
    const val GET_STARTED_LOGIN = "To get started, first enter your phone, email, or @username"
    const val FORGOT_PASSWORD = "Forgot password?"
    const val NEXT = "Next"
    const val PHONE_EMAIL_USERNAME = "Phone, email, or username"
    const val USERNAME_LENGTH_ERROR = "Username should be greater than $USERNAME_LENGTH characters"
    const val INVALID_USERNAME = "Invalid username"
    const val USERNAME_ALREADY_EXISTS = "Username already exists"
    const val EMAIL_ALREADY_EXISTS = "Email already exists"
    const val PHONE_NUMBER_ALREADY_EXISTS = "Phone number already exists"
    const val DEFAULT_ERROR_MESSAGE = "Something went wrong. Please try again later"
    const val UNAUTHORIZED_ACCESS = "Unauthorized Access"
    const val USER_DETAILS_NOT_FOUND = "User details not found"
    const val PASSWORD_LENGTH_ERROR = "Password should be greater than $PASSWORD_LENGTH characters"
    const val NO_UPPERCASE_ERROR = "Doesn't contains any uppercase character"
    const val NO_LOWERCASE_ERROR = "Doesn't contains any lowercase character"
    const val NO_DIGIT_ERROR = "Doesn't contains any digit"
    const val NO_SPECIAL_CHARACTER_ERROR = "Doesn't contains any special character"
    const val USER_AUTH_DETAILS_ERROR = "Username, phone number, email or password is incorrect"
    const val INVALID_EMAIL = "Invalid email address"
    const val INVALID_PHONE_NUMBER = "Invalid phone number"
    const val INVALID_LINK = "Invalid link"
    const val DB_WRITE_ERROR = "Not able to save the details at the moment. Please try again later"
    const val EMAIL_OR_PHONE_NUMBER_REQUIRED = "Email or phone number is required"
}