package utils

import utils.Constants.ConstValues.BIO_MAX_LENGTH
import utils.Constants.ConstValues.NAME_MAX_LENGTH
import utils.Constants.ConstValues.NAME_MIN_LENGTH
import utils.Constants.ConstValues.PASSWORD_MIN_LENGTH
import utils.Constants.ConstValues.TWEET_MAX_LENGTH
import utils.Constants.ConstValues.USERNAME_MIN_LENGTH

object Localization {
    fun format(key: String, vararg arguments: Any): String {
        var result = key
        for (a in arguments) {
            if (result.contains("%s")) {
                result = result.replaceFirst("%s", a.toString())
            } else {
                break
            }
        }
        return result
    }

    const val APP_NAME = "X"
    const val SPLASH_SCREEN_MESSAGE = "See what's happening in the world right now."
    const val CONTINUE_WITH_GOOGLE = "Continue with Google"
    const val CREATE_ACCOUNT = "Create Account"
    const val OR = "or"
    const val BY_SIGNING_UP = "By signing up, you agree to our"
    const val TERMS = "Terms"
    const val PRIVACY_POLICY = "Privacy Policy"
    const val AND = "and"
    const val COOKIE_USE = "Cookie Use"
    const val COMMA = ","
    const val PERCENTAGE = "%"
    const val FULL_STOP = "."
    const val WHITE_SPACE = " "
    const val HAVE_AN_ACCOUNT = "Have an account?"
    const val LOG_IN = "Log in"
    const val GET_STARTED_LOGIN = "To get started, first enter your phone, email, or @username"
    const val FORGOT_PASSWORD = "Forgot password?"
    const val NEXT = "Next"
    const val PHONE_EMAIL_USERNAME = "Phone, email, or username"
    const val USERNAME_LENGTH_ERROR =
        "Username should be greater than $USERNAME_MIN_LENGTH characters"
    const val NAME_LENGTH_ERROR =
        "Username should be in the range $NAME_MIN_LENGTH-$NAME_MAX_LENGTH characters"
    const val INVALID_USERNAME = "Invalid username"
    const val VALID_USERNAME = "Valid username"
    const val USERNAME_ALREADY_EXISTS = "Username already exists"
    const val EMAIL_ALREADY_EXISTS = "Email already exists"
    const val PHONE_NUMBER_ALREADY_EXISTS = "Phone number already exists"
    const val DEFAULT_ERROR_MESSAGE = "Something went wrong. Please try again later"
    const val UNAUTHORIZED_ACCESS = "Unauthorized Access"
    const val USER_DETAILS_NOT_FOUND = "User details not found"
    const val PASSWORD_LENGTH_ERROR =
        "Password should be greater than $PASSWORD_MIN_LENGTH characters"
    const val NO_UPPERCASE_ERROR = "Doesn't contains any uppercase character"
    const val NO_LOWERCASE_ERROR = "Doesn't contains any lowercase character"
    const val NO_DIGIT_ERROR = "Doesn't contains any digit"
    const val NO_SPECIAL_CHARACTER_ERROR = "Doesn't contains any special character"
    const val USER_AUTH_DETAILS_ERROR = "Username, phone number, email or password is incorrect"
    const val INVALID_EMAIL = "Invalid email address"
    const val INVALID_PHONE_NUMBER = "Invalid phone number"
    const val INVALID_LINK = "Invalid link"
    const val DB_WRITE_ERROR = "Not able to save the details at the moment. Please try again later"
    const val EMAIL_OR_PHONE_NUMBER_REQUIRED = "Email or phone number is required"
    const val USERNAME_OR_EMAIL_OR_PHONE_NUMBER_REQUIRED = "Phone, email, or username is required"
    const val LOADING = "Loading..."
    const val CREATE_YOUR_ACCOUNT = "Create your account"
    const val NAME = "Name"
    const val BIO = "Bio"
    const val PHONE_NUMBER_OR_EMAIL = "Phone number or email address"
    const val DATE_OF_BIRTH = "Date of birth"
    const val USE_EMAIL_INSTEAD = "Use email instead"
    const val USE_PHONE_INSTEAD = "Use phone instead"
    const val OTP_GENERATION_ERROR = "Not able to generate OTP at the moment. Please try again."
    const val OTP_GENERATE_SUCCESSFULLY = "OTP generate successfully"
    const val OTP_VERIFICATION_SUCCESS = "OTP verified successfully"
    const val OTP_VERIFICATION_INVALID = "Invalid OTP"
    const val OTP_VERIFICATION_ERROR = "Not able to verify OTP at the moment. Please try again."
    const val EMAIL = "Email"
    const val PHONE = "Phone"
    const val EMAIL_PHONE_ERROR_MESSAGE = "Please enter a valid %s."
    const val PHONE_NUMBER = "Phone number"
    const val DOB_SUPPORTING_TEXT =
        "This will not be shown publicly. Confirm your own age, even if this account is for a business, a pet, or something else."
    const val USER_PRESENT = "User details are present."
    const val OKAY = "Okay"
    const val WE_SENT_YOU_CODE = "We sent you a code"
    const val ENTER_BELOW_TO_VERIFY = "Enter it below to verify %s"
    const val WAITING_FOR_SMS = "Waiting for SMS to arrive"
    const val DID_NOT_RECEIVE_SMS = "Didn't receive SMS?"
    const val VERIFICATION_CODE = "Verification code"
    const val DID_NOT_RECEIVE_EMAIL = "Didn't receive email?"
    const val PROTECT_YOUR_ACCOUNT_WITH_PASSWORD = "Protect your account with a password"
    const val PASSWORD = "Password"
    const val CONFIRM_PASSWORD = "Confirm password"
    const val SHARE_PROFILE_IMAGE_USERNAME =
        "Add an username to share your profile image for others to find you easily"
    const val USERNAME = "Username"
    const val ACCOUNT_CREATED_SUCCESSFULLY = "Account created successfully"
    const val TOKEN_GENERATED_SUCCESSFULLY = "Account token generated successfully"
    const val USER_AUTHENTICATED = "User authenticated"
    const val DETAILS_FOUND = "Details found"
    const val BIO_MAX_LENGTH_ERROR = "Bio length should be less than $BIO_MAX_LENGTH characters"
    const val FOLLOWING = "Following"
    const val FOLLOWERS = "Followers"
    const val PROFILE = "Profile"
    const val PREMIUM = "Premium"
    const val COMMUNITIES = "Communities"
    const val BOOKMARKS = "Bookmarks"
    const val LISTS = "Lists"
    const val SPACES = "Spaces"
    const val MONETISATION = "Monetisation"
    const val INVALID_TWEET_LENGTH =
        "Tweet length should be in the range 1-$TWEET_MAX_LENGTH characters"
    const val INVALID_POLL_CHOICES = "At least one choice is needed for a poll"
    const val INVALID_POLL_TIMING = "Poll timing should be specified or correct"
    const val PARENT_TWEET_NOT_FOUND = "Need the parent tweet for this tweet"
    const val SCHEDULED_TWEET_IS_NOT_CORRECT =
        "Scheduled tweet time is not correct. Please select a valid time for."
    const val TWEET_CREATED_SUCCESSFULLY = "Your tweet is flying now."
    const val VALID_TWEET_NOT_FOUND = "Valid tweet not found. Please try again with a valid tweet."
    const val TWEET_VOTE_CASTED_SUCCESSFULLY = "Tweet vote casted successfully"
    const val VOTE_ALREADY_CASTED = "You have already casted your vote."
    const val POLL_VOTE_EXPIRED = "The poll has ended. You can't vote anymore."
    const val SERVER_IS_AVAILABLE = "Server is available"
    const val FOR_YOU = "For you"
    const val JUST_NOW = "just now"
    const val ONE_MINUTE_PAST = "one minute ago"
    const val X_MINUTES_PAST = "%s minutes ago"
    const val ABOUT_AN_HOUR_PAST = "about an hour ago"
    const val X_HOURS_PAST = "%s hours ago"
    const val ONE_DAY_PAST = "yesterday"
    const val X_DAYS_PAST = "%s days ago"
    const val ONE_WEEK_PAST = "a week ago"
    const val X_WEEKS_PAST = "%s weeks ago"
    const val ABOUT_A_MONTH_PAST = "about a month ago"
    const val X_MONTHS_PAST = "%s months ago"
    const val ABOUT_A_YEAR_PAST = "about a year ago"
    const val OVER_A_YEAR_PAST = "over a year ago"
    const val ALMOST_TWO_YEARS_PAST = "almost two years ago"
    const val X_YEARS_PAST = "%s years ago"
    const val ONE_MINUTE_FUTURE = "within one minute"
    const val X_MINUTES_FUTURE = "within %s minutes"
    const val ABOUT_AN_HOUR_FUTURE = "within about an hour"
    const val X_HOURS_FUTURE = "within %s hours"
    const val ONE_DAY_FUTURE = "tomorrow"
    const val X_DAYS_FUTURE = "within %s days"
    const val ONE_WEEK_FUTURE = "within one week"
    const val X_WEEKS_FUTURE = "within %s weeks"
    const val ABOUT_A_MONTH_FUTURE = "within about a month"
    const val X_MONTHS_FUTURE = "within %s months"
    const val ABOUT_A_YEAR_FUTURE = "within about a year"
    const val OVER_A_YEAR_FUTURE = "within over a year"
    const val ALMOST_TWO_YEARS_FUTURE = "within almost two years"
    const val X_YEARS_FUTURE = "within %s years"
    const val DAY = "day"
    const val DAYS = "days"
    const val HOUR = "hour"
    const val HOURS = "hours"
    const val MINUTE = "minute"
    const val MINUTES = "minutes"
    const val SECONDS = "seconds"
    const val LEFT = "left"
    const val VOTES = "votes"
    const val VOTE = "vote"
    const val FINAL_RESULTS = "Final results"
    const val POST = "Post"
    const val POST_ALL = "Post all"
    const val EVERYONE_CAN_REPLY = "Everyone can reply"
    const val WHATS_HAPPENING = "What's happening?"
    const val ADD_ANOTHER_TWEET = "Add another tweet"
    const val ASK_A_QUESTION = "Ask a question..."
    const val CHOICE = "Choice %s"
}