package utils

import utils.Constants.ConstValues.BIO_MAX_LENGTH
import utils.Constants.ConstValues.NAME_MAX_LENGTH
import utils.Constants.ConstValues.NAME_MIN_LENGTH
import utils.Constants.ConstValues.PASSWORD_MIN_LENGTH
import utils.Constants.ConstValues.TWEET_MAX_LENGTH
import utils.Constants.ConstValues.USERNAME_MIN_LENGTH

object Localization {
    const val APP_NAME = "X"
    const val SPLASH_SCREEN_MESSAGE = "See what's happening in the work right now."
    const val CONTINUE_WITH_GOOGLE = "Continue with Google"
    const val CREATE_ACCOUNT = "Create Account"
    const val OR = "or"
    const val BY_SIGNING_UP = "By signing up, you agree to our"
    const val TERMS = "Terms"
    const val PRIVACY_POLICY = "Privacy Policy"
    const val AND = "and"
    const val COOKIE_USE = "Cookie Use"
    const val COMMA = ","
    const val FULL_STOP = "."
    const val WHITE_SPACE = " "
    const val HAVE_AN_ACCOUNT = "Have an account?"
    const val LOG_IN = "Log in"
    const val GET_STARTED_LOGIN = "To get started, first enter your phone, email, or @username"
    const val FORGOT_PASSWORD = "Forgot password?"
    const val NEXT = "Next"
    const val PHONE_EMAIL_USERNAME = "Phone, email, or username"
    const val USERNAME_LENGTH_ERROR =
        "Username should be greater than $USERNAME_MIN_LENGTH characters"
    const val NAME_LENGTH_ERROR =
        "Username should be in the range $NAME_MIN_LENGTH-$NAME_MAX_LENGTH characters"
    const val INVALID_USERNAME = "Invalid username"
    const val VALID_USERNAME = "Valid username"
    const val USERNAME_ALREADY_EXISTS = "Username already exists"
    const val EMAIL_ALREADY_EXISTS = "Email already exists"
    const val PHONE_NUMBER_ALREADY_EXISTS = "Phone number already exists"
    const val DEFAULT_ERROR_MESSAGE = "Something went wrong. Please try again later"
    const val UNAUTHORIZED_ACCESS = "Unauthorized Access"
    const val USER_DETAILS_NOT_FOUND = "User details not found"
    const val PASSWORD_LENGTH_ERROR =
        "Password should be greater than $PASSWORD_MIN_LENGTH characters"
    const val NO_UPPERCASE_ERROR = "Doesn't contains any uppercase character"
    const val NO_LOWERCASE_ERROR = "Doesn't contains any lowercase character"
    const val NO_DIGIT_ERROR = "Doesn't contains any digit"
    const val NO_SPECIAL_CHARACTER_ERROR = "Doesn't contains any special character"
    const val USER_AUTH_DETAILS_ERROR = "Username, phone number, email or password is incorrect"
    const val INVALID_EMAIL = "Invalid email address"
    const val INVALID_PHONE_NUMBER = "Invalid phone number"
    const val INVALID_LINK = "Invalid link"
    const val DB_WRITE_ERROR = "Not able to save the details at the moment. Please try again later"
    const val EMAIL_OR_PHONE_NUMBER_REQUIRED = "Email or phone number is required"
    const val USERNAME_OR_EMAIL_OR_PHONE_NUMBER_REQUIRED =
        "Phone, email, or username is required"
    const val LOADING = "Loading..."
    const val CREATE_YOUR_ACCOUNT = "Create your account"
    const val NAME = "Name"
    const val BIO = "Bio"
    const val PHONE_NUMBER_OR_EMAIL = "Phone number or email address"
    const val DATE_OF_BIRTH = "Date of birth"
    const val USE_EMAIL_INSTEAD = "Use email instead"
    const val USE_PHONE_INSTEAD = "Use phone instead"
    const val OTP_GENERATION_ERROR = "Not able to generate OTP at the moment. Please try again."
    const val OTP_GENERATE_SUCCESSFULLY = "OTP generate successfully"
    const val OTP_VERIFICATION_SUCCESS = "OTP verified successfully"
    const val OTP_VERIFICATION_INVALID = "Invalid OTP"
    const val OTP_VERIFICATION_ERROR = "Not able to verify OTP at the moment. Please try again."
    const val EMAIL = "Email"
    const val PHONE = "Phone"
    const val EMAIL_PHONE_ERROR_MESSAGE = "Please enter a valid %s."
    const val PHONE_NUMBER = "Phone number"
    const val DOB_SUPPORTING_TEXT =
        "This will not be shown publicly. Confirm your own age, even if this account is for a business, a pet, or something else."
    const val USER_PRESENT = "User details are present."
    const val OKAY = "Okay"
    const val WE_SENT_YOU_CODE = "We sent you a code"
    const val ENTER_BELOW_TO_VERIFY = "Enter it below to verify %s"
    const val WAITING_FOR_SMS = "Waiting for SMS to arrive"
    const val DID_NOT_RECEIVE_SMS = "Didn't receive SMS?"
    const val VERIFICATION_CODE = "Verification code"
    const val DID_NOT_RECEIVE_EMAIL = "Didn't receive email?"
    const val PROTECT_YOUR_ACCOUNT_WITH_PASSWORD = "Protect your account with a password"
    const val PASSWORD = "Password"
    const val CONFIRM_PASSWORD = "Confirm password"
    const val SHARE_PROFILE_IMAGE_USERNAME =
        "Add an username to share your profile image for others to find you easily"
    const val USERNAME = "Username"
    const val ACCOUNT_CREATED_SUCCESSFULLY = "Account created successfully"
    const val TOKEN_GENERATED_SUCCESSFULLY = "Account token generated successfully"
    const val USER_AUTHENTICATED = "User authenticated"
    const val DETAILS_FOUND = "Details found"
    const val BIO_MAX_LENGTH_ERROR = "Bio length should be less than $BIO_MAX_LENGTH characters"
    const val FOLLOWING = "Following"
    const val FOLLOWERS = "Followers"
    const val PROFILE = "Profile"
    const val PREMIUM = "Premium"
    const val COMMUNITIES = "Communities"
    const val BOOKMARKS = "Bookmarks"
    const val LISTS = "Lists"
    const val SPACES = "Spaces"
    const val MONETISATION = "Monetisation"
    const val INVALID_TWEET_LENGTH =
        "Tweet length should be in the range 0-$TWEET_MAX_LENGTH characters"
    const val INVALID_POLL_CHOICES = "At least one choice is needed for a poll"
    const val INVALID_POLL_TIMING = "Poll timing should be specified or correct"
    const val PARENT_TWEET_NOT_FOUND = "Need the parent tweet for this tweet"
    const val SCHEDULED_TWEET_IS_NOT_CORRECT =
        "Scheduled tweet time is not correct. Please select a valid time for."
    const val TWEET_CREATED_SUCCESSFULLY = "Tweet created successfully"
    const val VALID_TWEET_NOT_FOUND = "Valid tweet not found. Please try again with a valid tweet."
    const val TWEET_VOTE_CASTED_SUCCESSFULLY = "Tweet vote casted successfully"
    const val VOTE_ALREADY_CASTED = "You have already casted your vote."
    const val POLL_VOTE_EXPIRED = "The poll has ended. You can't vote anymore."
}