package com.pradyotprakash.postscomments.app.localization

object TR {
    var appName = Translation.getString("appName")
    var okay = Translation.getString("okay")
    var noDataFoundError = Translation.getString("noDataFoundError")
    var welcomeToApp = Translation.getString("welcomeToApp")
    var email = Translation.getString("email")
    var password = Translation.getString("password")
    var confirmPassword = Translation.getString("confirmPassword")
    var login = Translation.getString("login")
    var register = Translation.getString("register")
    var signUp = Translation.getString("signUp")
    var signingUp = Translation.getString("signingUp")
    var alreadyHaveAccount = Translation.getString("alreadyHaveAccount")
    var confirmLogout = Translation.getString("confirmLogout")
    var cancel = Translation.getString("cancel")
    var createPost = Translation.getString("createPost")
    var postEditing = Translation.getString("postEditing")
    var title = Translation.getString("title")
    var text = Translation.getString("text")
    var send = Translation.getString("send")
    var name = Translation.getString("name")
    var posts = Translation.getString("posts")
    var surePostDelete = Translation.getString("surePostDelete")
    var sureCommentDelete = Translation.getString("sureCommentDelete")
    var comments = Translation.getString("comments")
    var add = Translation.getString("add")
    var createComment = Translation.getString("createComment")
    var commentEditing = Translation.getString("commentEditing")

}
