name: json_widget
description: "A widget which takes JSON an input and generates widget."
version: 0.0.1
homepage: https://github.com/pradyotprksh/development_learning

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.1

  flutter_test:
    sdk: flutter