name: json_widget
description: "A widget which takes JSON an input and generates widget."
version: 0.0.1
homepage: https://github.com/pradyotprksh/development_learning

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.5

  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.3

  hydrated_bloc: ^9.1.3

  logger: ^2.0.2+1

  replay_bloc: ^0.2.5

dev_dependencies:
  build_runner: ^2.4.7

  flutter_lints: ^3.0.1

  flutter_test:
    sdk: flutter

  json_annotation: ^4.8.1

  json_serializable: ^6.7.1