package com.pradyotprakash.futuresugoroku

object Constants {
    const val MAX_ROW = 5
    const val MAX_COL = MAX_ROW
    const val NUMBER_OF_ROOMS = MAX_ROW * MAX_COL
    const val NUMBER_OF_PLAYERS = 10
    const val NUMBER_OF_TURNS = 15
    const val START_PLAYER_POINTS = 15
    const val EXIT_DOOR = "EXIT_DOOR"
    val roomRowName = listOf("A", "B", "C", "D", "E")
    val roomColName = listOf(1, 2, 3, 4, 5)
    val RANDOM_PENALTY = listOf(
        1,
        2,
        4,
    )
    val EXIT_ROOM_POSITION = listOf(
        0,
        1,
        2,
        3,
        4,
        5,
        9,
        10,
        14,
        15,
        19,
        20,
        24,
    )
    val RANDOM_NAMES = listOf(
        "Saige Fuentes",
        "Bowen Higgins",
        "Leighton Kramer",
        "Kylan Gentry",
        "Amelie Griffith",
        "Franklin Sierra",
        "Marceline Avila",
        "Jaylen Blackwell",
        "Saoirse Conrad",
        "Dilan Wolf",
        "Jolene Fox",
        "Antonio Crosby",
        "Keily Meza",
        "Lucian Lee",
        "Scarlett Dickson",
        "Maxton Gill",
        "Jordan Dickerson",
        "Flynn Goodman",
        "Carolina Frederick",
        "Kase Sawyer",
        "Marina Yu",
        "Bryant Beard",
        "Ezra Doyle",
        "Kashton Green",
        "Zoe Durham",
        "Kellen Blackburn",
        "Frida Rhodes",
        "Titus Valdez",
        "Diana Wilcox",
        "Jerry Bernard",
        "Barbara Petersen",
        "Samson Conrad",
        "Bexley Pugh",
        "Judson Diaz",
        "Elena Stein",
        "Creed Sweeney",
        "Yara Velez",
        "Kareem McFarland",
        "Annika Bender",
        "Zavier Todd",
        "Zariah Guevara",
        "Tommy Shields",
        "Analia Byrd",
        "Cristian Parrish",
        "Tiana Morrow",
        "Kyree Santiago",
        "Nyla Grimes",
        "Harlan Nguyen",
        "Nova Andrews",
        "Lukas Fischer",
        "Maci Martinez",
        "Alexander Morse",
        "Kairi Franco",
        "Gage Hernandez",
        "Camila Acevedo",
        "Dakari Cardenas",
        "Raven Hull",
        "Salem Sparks",
        "Aisha Francis",
        "Harvey Valenzuela",
        "Henley Duffy",
        "Kyng Parra",
        "Dalary Rosario",
        "Jedidiah Faulkner",
        "Ansley Wilkerson",
        "Carmelo Nava",
        "Scout Clay",
        "Yosef Martinez",
        "Harper Bravo",
        "Genesis Morgan",
        "Delilah McClain",
        "Mitchell Frederick",
        "Sariyah Ho",
        "Morgan Mendoza",
        "Cora Villa",
        "Clay Delacruz",
        "Celine Marin",
        "Aldo Lim",
        "Giavanna Elliott",
        "Charlotte Bowen",
        "Katelyn Steele",
        "Dania Sandoval",
        "Jewel Bowers",
        "Melanie Yates",
        "Amaya Rosario",
        "Iliana Cisneros",
        "Silas Hurley",
        "Sean Nunez",
        "Fiona Sutton",
        "Marvin Lozano",
        "Jayvion Rice",
        "Kaine Horn",
        "Stephen Hendricks",
        "Fleur Riggs",
        "Sanaa Foley",
        "Samia Tapia",
        "Abraham Foley",
        "Connie J. Coleman",
        "Sherman Miner",
        "Kristen Gaytan"
    )
}