package com.pradyotprakash.themoviedbkmm.core.models

sealed interface Query {
    enum class SortBy(name: String) {
        popularity_asc("popularity.asc"),
        popularity_desc("popularity.desc"),
        revenue_asc("revenue.asc"),
        revenue_desc("revenue.desc"),
        primary_release_date_asc("primary_release_date.asc"),
        primary_release_date_desc("primary_release_date.desc"),
        vote_average_asc("vote_average.asc"),
        vote_average_desc("vote_average.desc"),
        vote_count_asc("vote_count.asc"),
        vote_count_desc("vote_count.desc"),
    }

    enum class Movie(name: String, defaultValue: Any?) {
        certification("certification", null),
        certification_gte("certification.gte", null),
        certification_lte("certification.lte", null),
        certification_country("certification_country", null),
        include_adult("include_adult", false),
        include_video("include_adult", false),
        language("language", "en-US"),
        page("page", 1),
        primary_release_year("primary_release_year", null),
        primary_release_date_gte("primary_release_date.gte", null),
        primary_release_date_lte("primary_release_date.lte", null),
        region("region", null),
        release_date_gte("release_date.gte", null),
        release_date_lte("release_date.lte", null),
        sort_by("sort_by", SortBy.popularity_desc.name),
        vote_average_gte("vote_average.gte", null),
        vote_average_lte("vote_average.lte", null),
        vote_count_gte("vote_count.gte", null),
        vote_count_lte("vote_count.lte", null),
        watch_region("watch_region", null),
        with_cast("with_cast", null),
        with_companies("with_companies", null),
        with_crew("with_crew", null),
        with_genres("with_genres", null),
        with_keywords("with_keywords", null),
        with_origin_country("with_origin_country", null),
        with_original_language("with_original_language", null),
        with_people("with_people", null),
        with_release_type("with_release_type", null),
        with_runtime_gte("with_runtime.gte", null),
        with_runtime_lte("with_runtime.lte", null),
        with_watch_monetization_types("with_watch_monetization_types", null),
        with_watch_providers("with_watch_providers", null),
        without_companies("without_companies", null),
        without_genres("without_genres", null),
        without_keywords("without_keywords", null),
        without_watch_providers("without_watch_providers", null),
        year("year", null),
    }
}