pipeline {
    agent any

    stages {
        stage('Build Android Project') {
            steps {
                echo 'Checking out android projects'
            }
        }

        stage('Parallel Builds') {
            parallel {
                stage('JenkinsLearning project') {
                    steps {
                        dir('./android/JenkinsLearning') {
                            script {
                                sh 'python3 ././android_script.py'
                            }
                        }
                    }
                }

                stage('Demo project') {
                    steps {
                        dir('./android/Demo') {
                            script {
                                sh 'python3 ././android_script.py'
                            }
                        }
                    }
                }
            }
        }
    }
}