pipeline {
    agent any

    stages {
        stage('Android Builds') {
            steps {
                echo 'Checking out Android projects'
                script {
                    def demoBuild = {
                        echo 'Checking out the Demo project'
                        dir('./android/Demo') {
                            echo 'sdk.dir=/Users/pradyotprakash/Library/Android/sdk' > local.properties
                            sh './gradlew build'
                        }
                    }

                    parallel demoBuild: demoBuild
                }
            }
        }
    }
}
