pipeline {
    agent any

    stages {
        stage('Parallel Build Android Project') {
            steps {
                echo 'Checking out android projects'
            }

            parallel {
                stage('JenkinsLearning project') {
                    steps {
                        dir('./android/JenkinsLearning') {
                            script {
                                writeFile file: 'local.properties', text: 'sdk.dir=/Users/pradyotprakash/Library/Android/sdk'
                                sh './gradlew build'
                            }
                        }
                    }
                }

                stage('Demo project') {
                    steps {
                        dir('./android/Demo') {
                            script {
                                writeFile file: 'local.properties', text: 'sdk.dir=/Users/pradyotprakash/Library/Android/sdk'
                                sh './gradlew build'
                            }
                        }
                    }
                }
            }
        }
    }
}
