from basics import numbers_basics, variable_assignments, strings_basics, string_slicing_indexing, \
    string_properties_methods, string_formatting, lists_basic, dictionaries_basics, tuples_basics, sets_basics, \
    booleans_basics, io_with_files_basics, comparison_operators_basics, comparison_with_logical_operators_basics
from src import log_info, Constants, print_new_line

log_info(Constants.Messages.STARTING_MESSAGE)
print_new_line()
log_info(Constants.Messages.LETS_START_WITH_PYTHON.format(Constants.Messages.NUMBERS_START))
numbers_basics()
print_new_line()
log_info(Constants.Messages.LETS_START_WITH_PYTHON.format(Constants.Messages.VARIABLES_ASSIGNMENT_START))
variable_assignments()
print_new_line()
log_info(Constants.Messages.LETS_START_WITH_PYTHON.format(Constants.Messages.STRINGS_START))
strings_basics()
print_new_line()
log_info(Constants.Messages.LETS_START_WITH_PYTHON.format(Constants.Messages.STRINGS_SLICING_INDEXING))
string_slicing_indexing()
print_new_line()
log_info(Constants.Messages.LETS_START_WITH_PYTHON.format(Constants.Messages.STRINGS_PROPERTIES_METHODS))
string_properties_methods()
print_new_line()
log_info(Constants.Messages.LETS_START_WITH_PYTHON.format(Constants.Messages.STRINGS_FORMATTING))
string_formatting()
print_new_line()
log_info(Constants.Messages.LETS_START_WITH_PYTHON.format(Constants.Messages.LISTS))
lists_basic()
print_new_line()
log_info(Constants.Messages.LETS_START_WITH_PYTHON.format(Constants.Messages.DICTIONARIES))
dictionaries_basics()
print_new_line()
log_info(Constants.Messages.LETS_START_WITH_PYTHON.format(Constants.Messages.TUPLES))
tuples_basics()
print_new_line()
log_info(Constants.Messages.LETS_START_WITH_PYTHON.format(Constants.Messages.SETS))
sets_basics()
print_new_line()
log_info(Constants.Messages.LETS_START_WITH_PYTHON.format(Constants.Messages.BOOLEANS))
booleans_basics()
print_new_line()
log_info(Constants.Messages.LETS_START_WITH_PYTHON.format(Constants.Messages.IO_WITH_FILES))
io_with_files_basics()
print_new_line()
log_info(Constants.Messages.LETS_START_WITH_PYTHON.format(Constants.Messages.COMPARISON_LOGICAL_OPERATORS))
comparison_operators_basics()
comparison_with_logical_operators_basics()
print_new_line()
