package com.project.pradyotprakash.rental.app.localization

/**
 * The translation key classes which holds the values of the string keys which is
 * required to be shown.
 */
object TR {
    var appName = Translation.getString("appName")
    var owner = Translation.getString("owner")
    var renter = Translation.getString("renter")
    var welcomeMessage = Translation.getString("welcomeMessage")
    var phone = Translation.getString("phone")
    var email = Translation.getString("email")
    var signInWithGoogle = Translation.getString("signInWithGoogle")
    var back = Translation.getString("back")
    var defaultErrorTitle = Translation.getString("defaultErrorTitle")
    var defaultErrorSubTitle = Translation.getString("defaultErrorSubTitle")
    var defaultErrorDescription = Translation.getString("defaultErrorDescription")
    var noDataFoundError = Translation.getString("noDataFoundError")
    var signIn = Translation.getString("signIn")
    var okay = Translation.getString("okay")
    var save = Translation.getString("save")
    var informationMessage = Translation.getString("informationMessage")
    var firstName = Translation.getString("firstName")
    var lastName = Translation.getString("lastName")
    var dobWithHelp = Translation.getString("dobWithHelp")
    var emailAddress = Translation.getString("emailAddress")
    var profession = Translation.getString("profession")
    var professionColon = Translation.getString("professionColon")
    var permanentAddress = Translation.getString("permanentAddress")
    var phoneNumber = Translation.getString("phoneNumber")
    var dataMissing = Translation.getString("dataMissing")
    var onlineImageDescription = Translation.getString("onlineImageDescription")
    var somethingWentWrongImageUpload = Translation.getString("somethingWentWrongImageUpload")
    var welcomeWithComma = Translation.getString("welcomeWithComma")
    var addAProperty = Translation.getString("addAProperty")
    var noPropertiesAvailable = Translation.getString("noPropertiesAvailable")
    var isForRental = Translation.getString("isForRental")
    var addressColon = Translation.getString("addressColon")
    var propertyForColon = Translation.getString("propertyForColon")
    var bathrooms = Translation.getString("bathrooms")
    var addANewProperty = Translation.getString("addANewProperty")
    var propertyName = Translation.getString("propertyName")
    var address = Translation.getString("address")
    var typeOfProperty = Translation.getString("typeOfProperty")
    var numberOfBathrooms = Translation.getString("numberOfBathrooms")
    var deposit = Translation.getString("deposit")
    var rent = Translation.getString("rent")
    var propertyPerks = Translation.getString("propertyPerks")
    var propertyAgreements = Translation.getString("propertyAgreements")
    var propertyImages = Translation.getString("propertyImages")
    var wherePropertyIs = Translation.getString("wherePropertyIs")
    var inSociety = Translation.getString("inSociety")
    var inApartment = Translation.getString("inApartment")
    var inHouse = Translation.getString("inHouse")
    var areYouOwner = Translation.getString("areYouOwner")
    var yes = Translation.getString("yes")
    var no = Translation.getString("no")
    var isForRentalWithQuestionMark = Translation.getString("isForRentalWithQuestionMark")
    var kindOfRentalAllowed = Translation.getString("kindOfRentalAllowed")
    var onlyFamilies = Translation.getString("onlyFamilies")
    var onlyBachelors = Translation.getString("onlyBachelors")
    var doesNotMatter = Translation.getString("doesNotMatter")
    var furnishedType = Translation.getString("furnishedType")
    var fullyFurnished = Translation.getString("fullyFurnished")
    var semiFurnished = Translation.getString("semiFurnished")
    var none = Translation.getString("none")
    var families = Translation.getString("families")
    var bachelors = Translation.getString("bachelors")
    var familiesBachelors = Translation.getString("familiesBachelors")
    var noFurniture = Translation.getString("noFurniture")
    var propertyDetailsNotFound = Translation.getString("propertyDetailsNotFound")
    var loading = Translation.getString("loading")
    var basicDetails = Translation.getString("basicDetails")
    var ownerDetails = Translation.getString("ownerDetails")
    var rentDetails = Translation.getString("rentDetails")
    var moneyDetails = Translation.getString("moneyDetails")
    var images = Translation.getString("images")
    var otherDetails = Translation.getString("otherDetails")
    var createdByColon = Translation.getString("createdByColon")
    var createdOnColon = Translation.getString("createdOnColon")
    var updatedOnColon = Translation.getString("updatedOnColon")
    var sendProposalToOwner = Translation.getString("sendProposalToOwner")
    var searchForRenter = Translation.getString("searchForRenter")
    var propertyListerDetails = Translation.getString("propertyListerDetails")
    
}
