on:
  push:
    branches:
      - main
    paths:
      - android/**
name: Android Projects
jobs:
  rental:
    name: Rental Code Checker
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
          distribution: 'adopt'
          cache: gradle
      - name: Checking Rental
        working-directory: ./android/Rental
        run: |
          chmod +x ./gradlew
          ./gradlew lint
          ./gradlew build
      - name: Send Message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            GitHub Action for android/Rental is completed with status ${{ job.status }} for ${{ github.ref }}.
  demo:
    name: Demo Code Checker
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
          distribution: 'adopt'
          cache: gradle
      - name: Checking Demo
        working-directory: ./android/Demo
        run: |
          chmod +x ./gradlew
          ./gradlew lint
          ./gradlew build
      - name: Send Message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            GitHub Action for android/Demo is completed with status ${{ job.status }} for ${{ github.ref }}.
  dicee:
    name: Dicee Code Checker
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
          distribution: 'adopt'
          cache: gradle
      - name: Checking Dicee
        working-directory: ./android/Dicee
        run: |
          chmod +x ./gradlew
          ./gradlew lint
          ./gradlew build
      - name: Send Message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            GitHub Action for android/Dicee is completed with status ${{ job.status }} for ${{ github.ref }}.
  flashChat:
    name: FlashChat Code Checker
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
          distribution: 'adopt'
          cache: gradle
      - name: Checking FlashChat
        working-directory: ./android/FlashChat
        run: |
          chmod +x ./gradlew
          ./gradlew lint
          ./gradlew build
      - name: Send Message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            GitHub Action for android/flashChat is completed with status ${{ job.status }} for ${{ github.ref }}.
  iAmRich:
    name: IAmRich Code Checker
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
          distribution: 'adopt'
          cache: gradle
      - name: Checking IAmRich
        working-directory: ./android/IAmRich
        run: |
          chmod +x ./gradlew
          ./gradlew lint
          ./gradlew build
      - name: Send Message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            GitHub Action for android/iAmRich is completed with status ${{ job.status }} for ${{ github.ref }}.
  twitter:
    name: Twitter Code Checker
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
          distribution: 'adopt'
          cache: gradle
      - name: Checking Twitter
        working-directory: ./android/Twitter
        run: |
          chmod +x ./gradlew
          ./gradlew lint
          ./gradlew build
      - name: Send Message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            GitHub Action for android/twitter is completed with status ${{ job.status }} for ${{ github.ref }}.
  whatsAppCompose:
    name: WhatsAppCompose Code Checker
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
          distribution: 'adopt'
          cache: gradle
      - name: Checking WhatsAppCompose
        working-directory: ./android/WhatsAppCompose
        run: |
          chmod +x ./gradlew
          ./gradlew lint
          ./gradlew build
      - name: Send Message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            GitHub Action for android/whatsAppCompose is completed with status ${{ job.status }} for ${{ github.ref }}.
  FindingFalcone:
    name: FindingFalcone Code Checker
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
          distribution: 'adopt'
          cache: gradle
      - name: Checking FindingFalcone
        working-directory: ./android/FindingFalcone
        run: |
          chmod +x ./gradlew
          ./gradlew lint
          ./gradlew build
      - name: Send Message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            GitHub Action for android/FindingFalcone is completed with status ${{ job.status }} for ${{ github.ref }}.
  PostsComments:
    name: PostsComments Code Checker
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
          distribution: 'adopt'
          cache: gradle
      - name: Checking PostsComments
        working-directory: ./android/PostsComments
        run: |
          chmod +x ./gradlew
          ./gradlew lint
          ./gradlew build
      - name: Send Message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            GitHub Action for android/PostsComments is completed with status ${{ job.status }} for ${{ github.ref }}.
  Notes:
    name: Notes Code Checker
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
          distribution: 'adopt'
          cache: gradle
      - name: Checking Notes
        working-directory: ./android/Notes
        run: |
          chmod +x ./gradlew
          ./gradlew lint
          ./gradlew build
      - name: Send Message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            GitHub Action for android/Notes is completed with status ${{ job.status }} for ${{ github.ref }}.
