on:
  push:
    branches:
      - main
    paths:
      - backend/**
name: Backend Projects
jobs:
  tasktracker:
    name: tasktracker Code Checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ricardochaves/python-lint@master
        with:
          python-root-list: "backend/tasktracker"
      - name: Send Message
        if: always()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            GitHub Action for backend/TaskTracker is completed with status ${{ job.status }} for ${{ github.ref }}.
  githubuseractivity:
    name: githubuseractivity Code Checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ricardochaves/python-lint@master
        with:
          python-root-list: "backend/githubuseractivity"
      - name: Send Message
        if: always()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            GitHub Action for backend/githubuseractivity is completed with status ${{ job.status }} for ${{ github.ref }}.
  expensetracker:
    name: expensetracker Code Checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ricardochaves/python-lint@master
        with:
          python-root-list: "backend/expensetracker"
      - name: Send Message
        if: always()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            GitHub Action for backend/expensetracker is completed with status ${{ job.status }} for ${{ github.ref }}.
  numberguessinggame:
    name: numberguessinggame Code Checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ricardochaves/python-lint@master
        with:
          python-root-list: "backend/numberguessinggame"
      - name: Send Message
        if: always()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            GitHub Action for backend/numberguessinggame is completed with status ${{ job.status }} for ${{ github.ref }}.
  UnitConverter:
    name: UnitConverter Code Checker
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '17'
      - name: Checking UnitConverter
        working-directory: ./backend/UnitConverter
        run: |
          chmod +x ./gradlew
          ./gradlew build
      - name: Send Message
        if: always()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            GitHub Action for backend/UnitConverter is completed with status ${{ job.status }} for ${{ github.ref }}.
  PersonalBlog:
    name: PersonalBlog Code Checker
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '17'
      - name: Checking PersonalBlog
        working-directory: ./backend/PersonalBlog
        run: |
          chmod +x ./gradlew
          ./gradlew build
      - name: Send Message
        if: always()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            GitHub Action for backend/PersonalBlog is completed with status ${{ job.status }} for ${{ github.ref }}.