on:
  push:
    branches:
      - main
    paths:
      - backend/**
name: Backend Projects
jobs:
  TaskTracker:
    name: TaskTracker Code Checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ricardochaves/python-lint@master
        with:
          python-root-list: "backend/TaskTracker"
      - name: Send Message
        if: always()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            GitHub Action for backend/TaskTracker is completed with status ${{ job.status }} for ${{ github.ref }}.
  githubuseractivity:
    name: githubuseractivity Code Checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ricardochaves/python-lint@master
        with:
          python-root-list: "backend/githubuseractivity"
      - name: Send Message
        if: always()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            GitHub Action for backend/githubuseractivity is completed with status ${{ job.status }} for ${{ github.ref }}.