on:
  push:
    branches:
      - main
    paths:
      - cs50/**
name: C Projects
jobs:
  rental:
    name: C Code Checker
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - name: Checking C Programs
        working-directory: ./cs50/c
        run: |
          gcc -Wall -Werror -Wextra -pedantic -std=gnu89 */*.c */*/*.c */*/*/*.c -o hello && ./hello
          gcc -Wall -Werror -Wextra -pedantic -std=gnu89 */*.c */*/*.c */*/*/*.c -o compare && ./compare
          gcc -Wall -Werror -Wextra -pedantic -std=gnu89 */*.c */*/*.c */*/*/*.c -o agree && ./agree
      - name: Send Message
        if: always()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            GitHub Action for cs50/c is completed with status ${{ job.status }} for ${{ github.ref }}.