on:
  push:
    branches:
      - main
    paths:
      - flutter/**
name: Flutter Projects
jobs:
  flublog:
    name: flublog Code Checker
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
      - run: flutter doctor
      - name: Checking flublog
        working-directory: ./flutter/flublog
        run: |
          flutter clean
          flutter pub outdated
          flutter pub upgrade
          flutter pub get
          flutter analyze
      - name: Send Message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            GitHub Action for flutter/flublog is completed with status ${{ job.status }} for ${{ github.ref }}.
  stackoverflow:
    name: stackoverflow Code Checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
      - run: flutter doctor
      - name: Checking stackoverflow
        working-directory: ./flutter/stackoverflow
        run: |
          flutter clean
          flutter pub outdated
          flutter pub upgrade
          flutter pub get
          flutter analyze
      - name: Send Message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            GitHub Action for flutter/stackoverflow is completed with status ${{ job.status }} for ${{ github.ref }}.
  second_hand_clothes:
    name: second_hand_clothes Code Checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
      - run: flutter doctor
      - name: Checking second_hand_clothes
        working-directory: ./flutter/second_hand_clothes
        run: |
          flutter clean
          flutter pub outdated
          flutter pub upgrade
          flutter pub get
          flutter analyze
      - name: Send Message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            GitHub Action for flutter/second_hand_clothes is completed with status ${{ job.status }} for ${{ github.ref }}.
  bang_bang:
    name: bang_bang Code Checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
      - run: flutter doctor
      - name: Checking bang_bang
        working-directory: ./flutter/bang_bang
        run: |
          flutter clean
          flutter pub outdated
          flutter pub upgrade
          flutter pub get
          flutter analyze
      - name: Send Message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            GitHub Action for flutter/bang_bang is completed with status ${{ job.status }} for ${{ github.ref }}.
  clean_architecture_example:
    name: clean_architecture_example Code Checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
      - run: flutter doctor
      - name: Checking clean_architecture_example
        working-directory: ./flutter/clean_architecture_example
        run: |
          flutter clean
          flutter pub outdated
          flutter pub upgrade
          flutter pub get
          flutter analyze
          flutter test
      - name: Send Message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            GitHub Action for flutter/clean_architecture_example is completed with status ${{ job.status }} for ${{ github.ref }}.
  whatsapp_clone:
    name: whatsapp_clone Code Checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
      - run: flutter doctor
      - name: Checking whatsapp_clone
        working-directory: ./flutter/whatsapp
        run: |
          flutter clean
          flutter pub outdated
          flutter pub upgrade
          flutter pub get
          flutter analyze
          flutter test
      - name: Send Message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            GitHub Action for flutter/whatsapp_clone is completed with status ${{ job.status }} for ${{ github.ref }}.
  fews:
    name: fews Code Checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
      - run: flutter doctor
      - name: Checking fews
        working-directory: ./flutter/fews
        run: |
          flutter clean
          flutter pub outdated
          flutter pub upgrade
          flutter pub get
          flutter test
      - name: Send Message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            GitHub Action for flutter/fews is completed with status ${{ job.status }} for ${{ github.ref }}.
  json_widget:
    name: json_widget Code Checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
      - run: flutter doctor
      - name: Checking json_widget
        working-directory: ./flutter/json_widget
        run: |
          flutter clean
          flutter pub outdated
          flutter pub upgrade
          flutter pub get
          flutter analyze
#          flutter test
      - name: Send Message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            GitHub Action for flutter/fews is completed with status ${{ job.status }} for ${{ github.ref }}.
