on:
  push:
    branches:
      - main
    paths:
      - go/**
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
name: Go Projects
jobs:
  learning:
    name: learning Code Checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: 'go/learning/hello/go.mod'
      - run: go version
      - name: Checking greetings
        working-directory: ./go/learning/greetings
        run: go test
      - name: Checking hello
        working-directory: ./go/learning/hello
        run: go vet && go run .
      - name: Checking workspace
        working-directory: ./go/learning/workspace
        run: go run pradyot.com/hello
      - name: Checking example
        working-directory: ./go/learning/workspace/example
        run: go test ./...
      - name: Send Message
        if: always()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            GitHub Action for go/learning is completed with status ${{ job.status }} for ${{ github.ref }}.
  stephen_udemy:
    name: stephen_udemy Code Checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
      - run: go version
      - name: Checking helloworld
        working-directory: ./go/stephen_udemy/helloworld
        run: go run main.go
      - name: Checking cards
        working-directory: ./go/stephen_udemy/cards
        run: go vet && go run . && go test
      - name: Checking evenodd
        working-directory: ./go/stephen_udemy/evenodd
        run: go run main.go
      - name: Checking structs
        working-directory: ./go/stephen_udemy/structs
        run: go vet && go run .
      - name: Checking maps
        working-directory: ./go/stephen_udemy/maps
        run: go run main.go
      - name: Checking interfaces
        working-directory: ./go/stephen_udemy/interfaces
        run: go run main.go
      - name: Checking interfaces_http
        working-directory: ./go/stephen_udemy/interfaces_http
        run: go run main.go
      - name: Checking interfaces_assignment_1
        working-directory: ./go/stephen_udemy/interfaces_assignment_1
        run: go run main.go
      - name: Checking interfaces_assignment_2
        working-directory: ./go/stephen_udemy/interfaces_assignment_2
        run: go run main.go example.txt
      - name: Send Message
        if: always()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            GitHub Action for go/stephen_udemy is completed with status ${{ job.status }} for ${{ github.ref }}.
