on:
  push:
    branches:
      - main
    paths:
      - kotlin/**
name: Kotlin Projects
jobs:
  data_structure:
    name: data_structure Code Checker
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - name: Checking data_structure
        working-directory: ./kotlin/data_structure
        run: kotlinc Main.kt
      - name: Send Message
        if: always()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            GitHub Action for kotlin/data_structure is completed with status ${{ job.status }} for ${{ github.ref }}.
  friends_tree:
    name: friends_tree Code Checker
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - name: Checking friends_tree
        working-directory: ./kotlin/friends_tree
        run: kotlinc Main.kt
      - name: Send Message
        if: always()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            GitHub Action for kotlin/friends_tree is completed with status ${{ job.status }} for ${{ github.ref }}.
  practice:
    name: practice Code Checker
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - name: Checking practice
        working-directory: ./kotlin/practice
        run: kotlinc Main.kt
      - name: Send Message
        if: always()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            GitHub Action for kotlin/practice is completed with status ${{ job.status }} for ${{ github.ref }}.
  udemy_course:
    name: udemy_course Code Checker
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - name: Checking udemy_course
        working-directory: ./kotlin/udemy_course
        run: kotlinc Main.kt
      - name: Send Message
        if: always()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            GitHub Action for kotlin/udemy_course is completed with status ${{ job.status }} for ${{ github.ref }}.
  pokedex:
    name: ktor/pokedex Code Checker
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - name: Checking ktor/pokedex
        working-directory: ./kotlin/ktor/pokedex
        run: |
          chmod +x ./gradlew
          ./gradlew build
          ./gradlew test
      - name: Send Message
        if: always()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            GitHub Action for kotlin/ktor/pokedex is completed with status ${{ job.status }} for ${{ github.ref }}.
  ds_algo:
    name: ds_algo Code Checker
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - name: Checking ds_algo
        working-directory: ./kotlin/ds_algo
        run: cat last_run.log
      - name: Send Message
        if: always()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            GitHub Action for kotlin/ds_algo is completed with status ${{ job.status }} for ${{ github.ref }}.
  leetcode_problems:
    name: leetcode_problems Code Checker
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - name: Checking leetcode_problems
        working-directory: ./kotlin/leetcode_problems
        run: cat last_run.log
      - name: Send Message
        if: always()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            GitHub Action for kotlin/leetcode_problems is completed with status ${{ job.status }} for ${{ github.ref }}.
  data_structures_algorithm:
    name: data_structures_algorithm Code Checker
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - name: Checking data_structures_algorithm
        working-directory: ./kotlin/data_structures_algorithm
        run: cat last_run.log
      - name: Send Message
        if: always()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            GitHub Action for kotlin/data_structures_algorithm is completed with status ${{ job.status }} for ${{ github.ref }}.