on:
  push:
    branches:
      - main
    paths:
      - rust/**
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
env:
  CARGO_TERM_COLOR: always
name: Rust Projects
jobs:
  hello-rust:
    name: hello-rust Code Checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Checking hello-rust
        working-directory: ./rust/hello-rust
        run: |
          cargo build
          cargo check
          cargo run
      - name: Send Message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            GitHub Action for rust/hello-rust is completed with status ${{ job.status }} for ${{ github.ref }}.
  guessing_number:
    name: guessing_number Code Checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Checking guessing_number
        working-directory: ./rust/guessing_number
        run: |
          cargo build
          cargo check
      - name: Send Message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            GitHub Action for rust/guessing_number is completed with status ${{ job.status }} for ${{ github.ref }}.
  common_programming_concepts:
    name: common_programming_concepts Code Checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Checking common_programming_concepts
        working-directory: ./rust/common_programming_concepts
        run: |
          cargo build
          cargo check
          cargo run
      - name: Send Message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            GitHub Action for rust/common_programming_concepts is completed with status ${{ job.status }} for ${{ github.ref }}.
  rustlings:
    name: rustlings Code Checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - uses: DavidAnson/markdownlint-cli2-action@v9
        with:
          globs: "exercises/**/*.md"
      - name: Run cargo fmt
        run: |
          cargo fmt --all -- --check
      - name: test
        runs-on: ${{ matrix.os }}
        strategy:
        matrix:
          os: [ubuntu-latest, windows-latest, macOS-latest]
        steps:
          - uses: actions/checkout@v3
          - uses: dtolnay/rust-toolchain@stable
          - uses: swatinem/rust-cache@v2
          - name: Run cargo test
            run: |
              cargo test
      - name: Send Message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            GitHub Action for rust/common_programming_concepts is completed with status ${{ job.status }} for ${{ github.ref }}.